server {
    listen 8082;

    server_name 4.230.16.250;

    root /var/www/devops-hackathon-de003-nguyendangduong/src;

    index index.html;

    access_log /var/log/nginx/nguyendanggduong-k24cntt2.access.log;
    error_log /var/log/nginx/nguyendanggduong-k24cntt2.error.log;

    location / {
        try_files $uri $uri/ =404;  
    }
}